CREATE DATABASE phan_tich;
USE phan_tich;

CREATE TABLE USERS (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    UserName VARCHAR(50) NOT NULL,
    Phone INT 
);

INSERT INTO USERS (UserName, Phone) VALUES ('Nguyen Van A', 0987654321);

ALTER TABLE USERS 
MODIFY COLUMN Phone VARCHAR(15) NOT NULL;
